columpioscam1:
  static_objects:
    bench:
    - 0.3985155143413598
    - 0.7321485481586403
    chair:
    - 0.26875
    - 0.8013888888888889
columpioscam2:
  static_objects:
    skateboard:
    - 0.5794921875
    - 0.6478298611111111
columpios_cam4:
  static_objects:
    bicycle:
    - 0.31417100694444444
    - 0.626755401234568
    skateboard:
    - 0.5751953125000001
    - 0.6989756944444445
columpioscam3:
  static_objects:
    skateboard:
    - 0.7536132812499999
    - 0.5901909722222222
columpios_tierra:
  static_objects:
    bench:
    - 0.4565216064453126
    - 0.9124710648148145
hundidocam1:
  static_objects:
    bench:
    - 0.7526622596153848
    - 0.6000747863247863
    chair:
    - 0.8572355769230772
    - 0.559909188034188
hundidocam2:
  static_objects:
    chair:
    - 0.9176939655172415
    - 0.7025478927203065
    bench:
    - 0.9000000000000001
    - 0.7191220238095238
    bicycle:
    - 0.8655133928571429
    - 0.8512896825396824
